export interface IResults {

    isResultsAvailable: boolean,
    uyDisplacements: number[] | null,
    uxDisplacements: number[] | null,
    ndForces: number[] | null,
    mxForces: number[] | null,
    myForces: number[] | null,
    ndMaxResistanceDiagramPoints: number[] | null,
    ndMinResistanceDiagramPoints: number[] | null,
    mxMinResistanceDiagramPoints: number[] | null,
    mxMaxResistanceDiagramPoints: number[] | null,
    myMinResistanceDiagramPoints: number[] | null,
    myMaxResistanceDiagramPoints: number[] | null,
    anglesResistanceDiagramPoints: number[] | null,
    lengthPoints: number[] | null,
    ndMaxSolicitingForces: number[] | null,
    ndMinSolicitingForces: number[] | null,
    mxMinSolicitingForces: number[] | null,
    mxMaxSolicitingForces: number[] | null,
    myMinSolicitingForces: number[] | null,
    myMaxSolicitingForces: number[] | null,
    anglesSolicitingForces: number[] | null,
}